finished sprint1
tjjordan/DYOD_SoSe21 pull request #1
Opened 2022-01-26 17:14 UTC by tjjordan

2022-01-30 01:49 UTC, mweisgut requested changes

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/table.cpp
> +    return ColumnID{it - names.begin()};
`std::distance` can be used here to calculate the distance between the iterators.

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/table.cpp
> +ColumnCount Table::column_count() const { return ColumnCount{static_cast<ColumnCount::base_type>(names.size())}; }
Why do you cast here but not in line 78?

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/table.cpp
> +    std::runtime_error("Invalid column_id.");
missing "throw"

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/table.cpp
> +  if (names.size() < column_id) {
You use the `at()` function in line 101, which includes bounds checks. Thus, the check here can be omitted.

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/table.cpp
> +  }
Same as above: check can be omitted since `at()` is used below.

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/table.cpp
> +  }
The check can be omitted since `at()` also performs bounds checks.

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/table.cpp
> +  }
see above

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.hpp
> +  std::unordered_map<std::string, std::shared_ptr<Table>> table_map;
Leading underscore for private/protected member variables is missing (see contribution guidelines).

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.cpp
> +  }
Since we don't handle exceptions in Hyrise, an assert would be sufficient.

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.cpp
> +  auto return_value = table_map.insert({name, std::move(table)});
Can be simplified by using `operator[]`, i.e., `table_map[name] = ...`

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.cpp
> +
Assert would be sufficient.

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.cpp
> +  }
Assert, see above

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.cpp
> +  return table_map.find(name)->second;
Can be simplified with `at()`

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.cpp
> +  for (auto& table: table_map) {
`table` can be const

2022-01-30 01:49 UTC, mweisgut commented on src/lib/storage/storage_manager.cpp
>    // Implementation goes here
Implementation is missing.

2022-01-30 14:04 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
> +  }
So we should use Assert or DebugAssert every time instead of throwing exceptions?

2022-01-31 09:19 UTC, tjjordan commented on src/lib/storage/value_segment.hpp
> +  std::vector<T> content;
adapted.

2022-01-31 09:20 UTC, tjjordan commented on src/lib/storage/value_segment.cpp
> +  return sizeof(content.at(0)) * content.size();
adapted.

2022-01-31 09:25 UTC, tjjordan commented on src/lib/storage/chunk.hpp
> +  std::vector<std::shared_ptr<BaseSegment>> chunk;
adapted.

2022-01-31 09:33 UTC, tjjordan commented on src/lib/storage/chunk.cpp
> +    ++i;
What would be an appropriate index variable?
I changed i to segment_number.

2022-01-31 09:34 UTC, tjjordan commented on src/lib/storage/chunk.cpp
> +  if (chunk.size() == 0) return 0;
adapted.

2022-01-31 09:35 UTC, tjjordan commented on src/lib/storage/chunk.cpp
> +  return chunk.at(0)->size();
adapted.

2022-01-31 09:38 UTC, tjjordan commented on src/lib/storage/chunk.cpp
> +    segment->append(values.at(i));
adapted.

2022-01-31 09:51 UTC, tjjordan commented on src/lib/storage/table.hpp
> +  std::vector<std::string> types;
adapted.

2022-01-31 09:51 UTC, tjjordan commented on src/lib/storage/table.hpp
> +  std::vector<std::string> names;
adapted.

2022-01-31 09:52 UTC, tjjordan commented on src/lib/storage/table.hpp
> +  std::vector<std::string> types;
adapted.

2022-01-31 09:52 UTC, tjjordan commented on src/lib/storage/table.cpp
> +  DebugAssert(values.size() == column_count(), "Length muissmatch.");
adapted.

2022-01-31 09:53 UTC, tjjordan commented on src/lib/storage/table.cpp
> +    for (auto& type : types) {
adapted.

2022-01-31 09:53 UTC, tjjordan commented on src/lib/storage/table.cpp
> +  for (auto& chunk: chunks) {
adapted.

2022-01-31 10:04 UTC, tjjordan commented on src/lib/storage/table.cpp
> +    return ColumnID{it - names.begin()};
adapted.

2022-01-31 10:06 UTC, tjjordan commented on src/lib/storage/table.cpp
> +ColumnCount Table::column_count() const { return ColumnCount{static_cast<ColumnCount::base_type>(names.size())}; }
Figured out later casting isn't necessary here.
Removed the cast.

2022-01-31 10:07 UTC, tjjordan commented on src/lib/storage/table.cpp
> +    std::runtime_error("Invalid column_id.");
adapted.

2022-01-31 10:12 UTC, tjjordan commented on src/lib/storage/table.cpp
> +  if (names.size() < column_id) {
adapted.

2022-01-31 10:12 UTC, tjjordan commented on src/lib/storage/table.cpp
> +  }
adapted.

2022-01-31 10:13 UTC, tjjordan commented on src/lib/storage/table.cpp
> +  }
adapted.

2022-01-31 10:13 UTC, tjjordan commented on src/lib/storage/table.cpp
> +  }
adapted.

2022-01-31 10:16 UTC, tjjordan commented on src/lib/storage/storage_manager.hpp
> +  std::unordered_map<std::string, std::shared_ptr<Table>> table_map;
adapted.

2022-01-31 10:36 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
> +
adapted.

2022-01-31 10:37 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
> +  }
adapted.

2022-01-31 10:38 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
> +  return table_map.find(name)->second;
adapted.

2022-01-31 10:39 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
> +  for (auto& table: table_map) {
adapted.

2022-01-31 10:43 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
>    // Implementation goes here
implemented.

2022-02-01 11:38 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
> +  auto return_value = table_map.insert({name, std::move(table)});
adapted.

2022-02-02 09:27 UTC, merged