Sprint2
tjjordan/DYOD_SoSe21 pull request #2
Opened 2022-02-09 10:24 UTC by tjjordan

Finished work on sprint 2.

2022-02-10 14:25 UTC, mweisgut commented
Could you please separate the implementation of the dictionary segment into a header file and a source file?

2022-02-14 14:25 UTC, mweisgut requested changes
Partially reviewed.
Review will be continued at `dictionary_segment.hpp`

2022-02-14 14:25 UTC, mweisgut commented on src/lib/storage/chunk.cpp
> +std::shared_ptr<BaseSegment> Chunk::get_segment(ColumnID column_id) const { return _chunk.at(column_id); }
Consider using `[]` here with a `DebugAssert` rather than `at(...)` for performance reasons.

2022-02-14 14:25 UTC, mweisgut commented on src/lib/storage/table.cpp
> +    const auto& segment = uncompressed_chunk.get_segment(ColumnID(column_id));
Prefer `ColumnID{column_id}`, see https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-list

2022-02-15 12:08 UTC, mweisgut requested changes
I'll continue with the StorageManager tomorrow.

2022-02-15 12:08 UTC, mweisgut commented on src/lib/storage/dictionary_segment.hpp
> +    return INVALID_VALUE_ID;
Code redundancy: We can use `ValueID lower_bound(T value) const` here. For this, we have to cast the `AllTypeVariant` into its native data type. This can be done with `type_cast` (see `type_cast.hpp`).

2022-02-15 12:08 UTC, mweisgut commented on src/lib/storage/dictionary_segment.hpp
> +    return INVALID_VALUE_ID;
Analogous to `lower_bound`, `std::upper_bound` can be used here.

2022-02-15 12:08 UTC, mweisgut commented on src/lib/storage/dictionary_segment.hpp
> +    return INVALID_VALUE_ID;
Analogous to `lower_bound`, we can use the above function here.

2022-02-16 10:03 UTC, tjjordan commented on src/lib/storage/chunk.hpp
> +  std::vector<std::shared_ptr<BaseSegment>> _chunk;
Already changed this in the master branch.

2022-02-16 10:33 UTC, mweisgut commented on src/lib/storage/dictionary_segment.hpp
> +    const auto& values = std::dynamic_pointer_cast<ValueSegment<T>>(base_segment)->values();
Not resolved yet.

2022-02-16 10:36 UTC, mweisgut commented on src/lib/storage/dictionary_segment.hpp
> +    } else { Assert(1==0, "Too many unique values."); }
Not resolved yet.

2022-02-16 10:37 UTC, mweisgut commented on src/lib/storage/dictionary_segment.hpp
> +    for (size_t attribute_index = 0; attribute_index < values.size(); ++attribute_index) {
not resolved yet.

2022-02-16 10:51 UTC, tjjordan commented on src/lib/storage/storage_manager.cpp
> +  for (auto& table : table_map) {
already changed at master

2022-02-16 10:51 UTC, tjjordan commented on src/lib/storage/table.hpp
>    std::vector<std::string> types;
already changed at master

2022-02-16 10:54 UTC, tjjordan commented on src/lib/storage/table.cpp
> +ChunkOffset Table::target_chunk_size() const { return chunk_size; }
already changed at master

2022-02-16 10:55 UTC, tjjordan commented on src/lib/storage/table.cpp
> +const std::vector<std::string>& Table::column_names() const { return names; }
already changed at master

2022-02-16 11:38 UTC, mweisgut commented
Right now, the test coverage is not sufficient, especially for the `table.cpp` and `dictionary.cpp`. Could you please add additional test cases to achieve a high line coverage ratio (ideally 100%) for `chunk.cpp`, `dictionary_segment.cpp`, `storage_manager.cpp`, `table.cpp`, and `value_segment.cpp`? 
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/20044656/154256672-c1e8524c-83db-4027-a3c7-988b04330b8f.png">

2022-02-21 13:46 UTC, merged