Finished Sprint 3
tjjordan/DYOD_SoSe21 pull request #4
Opened 2022-03-07 14:12 UTC by tjjordan

2022-03-12 15:06 UTC, mweisgut requested changes
🚀

2022-03-12 15:06 UTC, mweisgut commented on src/lib/storage/table.cpp
> +  }
Can you come up with a scenario in which the last chunk is empty and more this chunk is not the only chunk stored in the table?

Isn't it sufficient here to only replace the last chunk (pointer) by the chunk (pointer) to be emplaced, if the last chunk is empty?

2022-03-12 15:06 UTC, mweisgut commented on src/lib/storage/table.cpp
> +void Table::emplace_chunk(std::shared_ptr<Chunk> chunk) {
pointer can be const

2022-03-12 15:06 UTC, mweisgut commented on src/lib/storage/reference_segment.cpp
> +  return selected_chunk.get_segment(referenced_column_id())->operator[](selected_row.chunk_offset);
Use `[selected_row.chunk_offset]` over `operator[](selected_row.chunk_offset)`.

2022-03-12 20:19 UTC, mweisgut commented
Also, the lint script reports some issues, which should be fixed.

2022-03-18 14:26 UTC, tjjordan commented on src/lib/operators/table_scan.cpp
> +  }
Would an exception be also suitable in this case?
Since an invalid ColumnID would be the result of faulty user input.

2022-03-29 07:12 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +  }
I would still tend to use an `assert` here so that we crash immediately in a faulty state. Regarding the user input: from an end-to-end perspective in Hyrise, `column_id` would be determined within the SQL pipeline by the LQP translator. Thus, it would not be a parameter specified by the user.

2022-03-29 07:21 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +      return [](auto left_operant, auto right_operand) { return left_operant == right_operand; };
```suggestion
      return [](auto left_operand, auto right_operand) { return left_operant == right_operand; };
```

2022-03-29 07:21 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +      return [](auto left_operant, auto right_operand) { return left_operant != right_operand; };
operand, see above

2022-03-29 07:21 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +      return [](auto left_operant, auto right_operand) { return left_operant < right_operand; };
operand, see above

2022-03-29 07:21 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +      return [](auto left_operant, auto right_operand) { return left_operant <= right_operand; };
operand, see above

2022-03-29 07:21 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +      return [](auto left_operant, auto right_operand) { return left_operant > right_operand; };
operand, see above

2022-03-29 07:21 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +      return [](auto left_operant, auto right_operand) { return left_operant >= right_operand; };
operand, see above

2022-03-29 07:40 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +    const auto value = selected_chunk.get_segment(_column_id)->operator[](selected_row.chunk_offset);
`operator[]` of the `ReferenceSegment` returns an `AllTypeVariant`, for which accessing the value is expensive. It is possible here not to use that operator.

2022-03-29 08:12 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +  }
Instead of comparing the values, which requires an indirection, we can directly work on the value ids. The current solution performs a value lookup for each ValueID in the attribute vector; this is expensive.

2022-03-29 08:22 UTC, mweisgut commented on src/lib/operators/table_scan.cpp
> +  ValueID search_value_id = typed_segment->lower_bound(search_value());
This is never used. However, the idea is correct: we want to compare the attribute vector's value ids with the search value id rather than comparing the values.

2022-05-28 12:47 UTC, merged